[WFX-173] Introduce new background script to extensibles to allow ren…
BrowserWorks/waterfox pull request #2183
Opened 2021-07-26 09:53 UTC by adamp01

…dering additional preference checkboxes on about:preferences

2021-08-02 10:26 UTC, MrAlex94 commented
All looks good. Just a couple of UI/X changes to make it more inline with current vernacular throughout the UI:

- Disable `Copy URL only from active tab` by default
- Use `Link`/`Links` instead of `URL`/`URLs`

URL is definitely the correct usage, but since the browser and the average user uses link in it's place, might as well keep it consistent with that.

2021-08-02 15:17 UTC, MrAlex94 requested changes
All looks good. Just a couple of UI/X changes to make it more inline with current vernacular throughout the UI:

- Disable `Copy URL only from active tab` by default
- Use `Link`/`Links` instead of `URL`/`URLs`

URL is definitely the correct usage, but since the browser UI and the average user uses link in it's place, might as well keep it consistent with that. I know hawkeye implemented it with URLs but might as well fix it up now before we forget 😬

2021-08-04 09:03 UTC, hawkeye116477 commented
`I know hawkeye implemented it with URLs`

In principle, I borrowed this from Cyberfox and didn't changed author's entries.

2021-08-04 14:36 UTC, MrAlex94 approved these changes

2021-08-04 14:37 UTC, merged