Updated Polish translation.
BrowserWorks/waterfox pull request #2666
Opened 2022-04-08 11:17 UTC by kamil445

Updated Polish translation.

Also I added extensibles.ftl file mentioned here https://github.com/WaterfoxCo/Waterfox/pull/2662 to translate more words.

2022-04-11 11:30 UTC, adamp01 approved these changes
lgtm - will merge after https://github.com/WaterfoxCo/Waterfox/pull/2662

2022-04-11 13:37 UTC, adamp01 commented
@kamil445 - We are going to be adding another translation today:
```
### aboutDialog
update-updateCheckDisabled = Checking for updates is currently disabled.
```

2022-04-11 14:09 UTC, hawkeye116477 requested changes

2022-04-11 14:09 UTC, hawkeye116477 commented on browser/locales/l10n/pl/browser/browser/extensibles.ftl
> +    .label = Otwórz wszytkie w prywatnych kartach
You eaten one letter.

(wszy **s** tkie)

It's little more of that, so search and replace all :smile:.

2022-04-11 17:44 UTC, kamil445 commented
> @kamil445 - We are going to be adding another translation today:
> 
> ```
> ### aboutDialog
> update-updateCheckDisabled = Checking for updates is currently disabled.
> ```

Thank you for information, i've added translation.

2022-04-11 17:47 UTC, kamil445 commented on browser/locales/l10n/pl/browser/browser/extensibles.ftl
> +    .label = Otwórz wszytkie w prywatnych kartach
Thanks, is corrected now :)

2022-04-12 13:51 UTC, hawkeye116477 approved these changes

2022-09-01 14:52 UTC, MrAlex94 commented
Sorry for the delay!

This is now handled by Crowdin and will be live in G5 Beta 2. 

435bd9a2683e09600655dc322098650479a51a5a

2022-09-01 14:52 UTC, closed without merging