[QOL] Disable the black screen transition when going full-screen
BrowserWorks/waterfox pull request #778
Opened 2018-11-01 19:17 UTC by Joshua-Ashton

This transition is way too long, and is incredibly irritating.

Me and everyone I know who uses Water/Firefox disables this too.
It would be a great QoL change to get this merged in for default.

Cheers!
 - Josh

2018-11-03 06:45 UTC, grahamperrin commented
I never noticed a black screen. 

about:config?filter=full-screen-api.transition-duration.enter finds a default of 0 (zero) with Waterfox 56.2.3 on FreeBSD.

2018-11-03 22:50 UTC, Joshua-Ashton commented
On FreeBSD I am assuming it compiles with MOZ_WIDGET_GTK or something which is why the default would be zero.

You are welcome to like the effect, however:

It still lags greatly and takes 1.61 seconds (I timed it, and it's way longer than set) to transition for me when set to the default values. Other people I know also experience this same issue. I have tried this across Windows and Linux and the issue still persists.

That's 1.61 seconds that I can't do anything with my computer, or consume the content I asked for!

It adds very little to the browsing experience -- in fact it hinders it and actively prohibits me and others from accessing the content that we chose to make full-screen for a fairly extended period of time.

If something doesn't work properly (eg. the timings don't work correctly due to lag) and it hinders a user, it really shouldn't be enabled by default.

2018-11-03 22:52 UTC, Joshua-Ashton commented
Not only that, but it makes the video I am watching lag to a crawl while it does the fade in/out animation, it's really painful...

2018-11-07 19:21 UTC, WagnerGMD requested changes
**You have forgot this one  !**
```
pref("full-screen-api.warning.timeout",0);
// According to my memories, I believe the original value is :
pref("full-screen-api.warning.timeout",3000);
```

2018-11-08 01:36 UTC, Joshua-Ashton commented
This doesn't have an effect on the transition, but just the warning that shows up. That doesn't really bother me that much, but yeah it's not really necessary either.

2018-12-22 00:46 UTC, Joshua-Ashton commented
Helloooooooooooooooooooooooooooooooooooooooooooooooo?

2019-01-20 08:50 UTC, grahamperrin commented
Sought other reports of annoyance in the subreddit for Waterfox, I found this from 2016: https://redd.it/415ffm

Back to 2015, https://redd.it/3rzdyg (liking the fading, if not too long) referred to this Mozilla bug (RESOLVED FIXED in Firefox 42): 

- [1185775 - The transition for entering and exiting fullscreen is too long](https://bugzilla.mozilla.org/show_bug.cgi?id=1185775)

More recent: 

- [1209829 - [meta] Tracking bug for Fullscreen API issues](https://bugzilla.mozilla.org/show_bug.cgi?id=1209829)

– and in its [dependency tree](https://bugzilla.mozilla.org/showdependencytree.cgi?id=1209829&hide_resolved=1): 

- [1187769 - [meta] Full screen transition is black for too long](https://bugzilla.mozilla.org/show_bug.cgi?id=1187769)

2019-02-04 19:48 UTC, Joshua-Ashton commented
Hellooooooooooooooooooooooooo?

2019-07-09 22:59 UTC, regs01 commented
I find this smooth transition pretty good. While crude Chrome and Edge transitions are quite annoying for eyes.

2019-10-04 15:17 UTC, closed without merging